### ISSUE TITLE
add image support

### ISSUE THREAD

**Issue by gladiusThayalarajan** [gladiusThayalarajan/vesinnovators#1]
Need to add image support to project

**Comment by gladiusThayalarajan** [comment]
![img_20150829_020021](https://cloud.githubusercontent.com/assets/12659067/9567498/f68c5e20-4f4a-11e5-80f4-89eb3c5af523.jpg)

**Comment by jdayanithi** [comment]
Working on with boostrap image upload component

**Comment by gladiusThayalarajan** [comment]
sure , that looks good

**Comment by gladiusThayalarajan** [comment]
![vz daya 20150830_214009](https://cloud.githubusercontent.com/assets/12659067/9568193/27286c6c-4f60-11e5-8622-b1debc023c0c.jpg)

**Comment by gladiusThayalarajan** [comment]
fix is working after latest deployment , Thanks
